# -*- mode: ruby -*-
# vi: set ft=ruby :

$control_installation_script= <<-SCRIPT
sudo k3s server &
sudo k3s kubectl get node
SCRIPT

$agent_installation_script= <<-SCRIPT
# NODE_TOKEN comes from /var/lib/rancher/k3s/server/node-token on your server
sudo k3s agent --server https://myserver:6443 --token ${NODE_TOKEN}
SCRIPT



Vagrant.configure("2") do |config|

  config.vm.box = "fakouyat/ubuntu"
  config.vm.box_url = "./boxes/package.box"

  #Disk
  config.vm.disk :disk, size: "100GB", primary: true

  #SSH configuration
  config.ssh.private_key_path = "./.ssh/vagrant_key.pub"
  config.ssh.username = "vagrant"
  config.ssh.forward_agent = true

  #Controller
  config.vm.define "fakouyatS" do |control|
    control.vm.hostname = "fakouyatS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider 'virtualbox' do |vb|
      vb.customize ["modifyvm", :id, "--name", "fakouyatS"]
      vb.memory = 1024
      vb.cpus = 1
    end
    config.vm.provision "shell", $control_installation_script
  end

  #Worker
  config.vm.define "fakouyatSW" do |worker|
    worker.vm.hostname = "fakouyatSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider 'virtualbox' do |vb|
      vb.customize ["modifyvm", :id, "--name", "fakouyatSW"]
      vb.memory = 1024
      vb.cpus = 1
    end
    config.vm.provision "shell", $agent_installation_script
  end

end
