apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rock-paper-scissors-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pgiraude/pgiraude.git
    targetRevision: HEAD
    path: p3/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
