# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

control_installation_script= <<-SCRIPT
  sudo apt update
  sudo apt install -y curl
  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" sh -
  sleep 10
  if [ -f "/etc/rancher/k3s/k3s.yaml" ]; then
    sudo chmod 644 /etc/rancher/k3s/k3s.yaml
    sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/
  else
    echo "ERROR: k3s.yaml not found!" >&2
    exit 1
  fi
  NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
  while [ ! -e ${NODE_TOKEN} ]; do sleep 1; done
  sudo cp ${NODE_TOKEN} /vagrant/
SCRIPT


agent_installation_script= <<-SCRIPT
 curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" K3S_URL=https://#{SERVER_IP} K3S_TOKEN=$(sudo cat /vagrant/node-token) sh -
  sleep 10
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  #controller
  config.vm.define "fakouyatS" do |control|
    control.vm.hostname = "fakouyatS"
    control.vm.network "private_network", ip: SERVER_IP
    control.vm.provider 'virtualbox' do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    #control.vm.provision "shell", inline: control_installation_script
  end

  #Worker
  config.vm.define "fakouyatSW" do |worker|
    worker.vm.hostname = "fakouyatSW"
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider 'virtualbox' do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    #worker.vm.provision "shell", inline: agent_installation_script
  end

end
