# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

path_to_k3s_server_script = "./scripts/k3s_as_server.sh"
path_to_agent_script = "./scripts/k3s_as_agent.sh"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  #controller
  config.vm.define "fakouyatS" do |control|
    control.vm.hostname = "fakouyatS"
    control.vm.network "private_network", ip: SERVER_IP
    control.vm.provider 'virtualbox' do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    control.vm.provision "shell", path: path_to_k3s_server_script
  end

  #Worker
  config.vm.define "fakouyatSW" do |worker|
    worker.vm.hostname = "fakouyatSW"
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider 'virtualbox' do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: path_to_agent_script
  end

end
